export const initialData = {
  products: [
    { id: 'p1', code: 'HE-110S', name: '壁挂式取暖器', model: '小型款' },
    { id: 'p2', code: 'HE-110M', name: '壁挂式取暖器', model: '标准款' },
    { id: 'p3', code: 'HE-110L', name: '壁挂式取暖器', model: '大型款' },
  ],
  materials: [
    { id: 'm1', code: 'PCB-CTRL-01', name: '控制板', category: '电子件', unit: '件', procurementLeadTimeDays: 14 },
    { id: 'm2', code: 'PCB-PWR-01', name: '电源板', category: '电子件', unit: '件', procurementLeadTimeDays: 12 },
    { id: 'm3', code: 'CER-HEAT-01', name: '陶瓷片', category: '发热件', unit: '片', procurementLeadTimeDays: 20 },
    { id: 'm4', code: 'PKG-BOX-01', name: '包装箱', category: '包装件', unit: '个', procurementLeadTimeDays: 7 },
    { id: 'm5', code: 'CAB-PWR-01', name: '电源线', category: '线材', unit: '根', procurementLeadTimeDays: 10 },
    { id: 'm6', code: 'CASE-ABS-01', name: '外壳', category: '结构件', unit: '套', procurementLeadTimeDays: 18 },
    { id: 'm7', code: 'FAN-DC-01', name: '风扇', category: '机电件', unit: '个', procurementLeadTimeDays: 16 },
    { id: 'm8', code: 'KNOB-01', name: '旋钮', category: '结构件', unit: '个', procurementLeadTimeDays: 9 },
    { id: 'm9', code: 'LBL-01', name: '标签', category: '包装件', unit: '张', procurementLeadTimeDays: 3 },
    { id: 'm10', code: 'MAN-ZH-01', name: '说明书', category: '包装件', unit: '本', procurementLeadTimeDays: 5 },
  ],
  bom: [
    ...['p1', 'p2', 'p3'].flatMap((productId) => [
      { productId, materialId: 'm1', qtyPerProduct: 1 },
      { productId, materialId: 'm2', qtyPerProduct: 1 },
      { productId, materialId: 'm4', qtyPerProduct: 1 },
      { productId, materialId: 'm5', qtyPerProduct: 1 },
      { productId, materialId: 'm6', qtyPerProduct: 1 },
      { productId, materialId: 'm7', qtyPerProduct: 1 },
      { productId, materialId: 'm8', qtyPerProduct: 1 },
      { productId, materialId: 'm9', qtyPerProduct: 1 },
      { productId, materialId: 'm10', qtyPerProduct: 1 },
    ]),
    { productId: 'p1', materialId: 'm3', qtyPerProduct: 2 },
    { productId: 'p2', materialId: 'm3', qtyPerProduct: 3 },
    { productId: 'p3', materialId: 'm3', qtyPerProduct: 4 },
  ],
  inventory: [
    { materialId: 'm1', stockQty: 150, safetyStock: 20, leadTimeDays: 14 },
    { materialId: 'm2', stockQty: 180, safetyStock: 20, leadTimeDays: 12 },
    { materialId: 'm3', stockQty: 500, safetyStock: 80, leadTimeDays: 20 },
    { materialId: 'm4', stockQty: 120, safetyStock: 30, leadTimeDays: 7 },
    { materialId: 'm5', stockQty: 300, safetyStock: 40, leadTimeDays: 10 },
    { materialId: 'm6', stockQty: 130, safetyStock: 25, leadTimeDays: 18 },
    { materialId: 'm7', stockQty: 210, safetyStock: 30, leadTimeDays: 16 },
    { materialId: 'm8', stockQty: 175, safetyStock: 25, leadTimeDays: 9 },
    { materialId: 'm9', stockQty: 1000, safetyStock: 100, leadTimeDays: 3 },
    { materialId: 'm10', stockQty: 165, safetyStock: 20, leadTimeDays: 5 },
  ],
  orders: [
    { productId: 'p1', orderQty: 100 },
    { productId: 'p2', orderQty: 50 },
    { productId: 'p3', orderQty: 20 },
  ],
  orderEvaluationRecords: [
    {
      id: 'EV-DEMO-001',
      recordType: 'orderEvaluation',
      status: 'analyzed',
      input: {
        productId: 'p1',
        plannedQty: 300,
        requiredDate: '2026-07-12',
        asOfDate: '2026-06-27',
        note: '客户询问 300 台 15 天交付',
      },
      summary: {
        riskLevel: 'critical',
        keyRiskMaterialCount: 3,
        procurementConfirmCount: 2,
        warehouseConfirmCount: 1,
        canMeetRequiredDate: false,
      },
      analysisSnapshot: {
        generatedAt: '2026-06-27T10:30:00',
        source: 'delivery-risk-analysis',
        materialRisks: [],
        procurementRecommendations: [],
        warehouseFeedbackHints: [],
      },
      businessBoundary: {
        isOfficialSalesOrder: false,
        affectsInventory: false,
        reservesInventory: false,
        createsPurchaseOrder: false,
        entersFinance: false,
        hasCostAccounting: false,
      },
      futureLinks: {
        salesOrderId: null,
        purchaseRequestIds: [],
        inventoryTransactionIds: [],
        costSnapshotId: null,
        financeReferenceId: null,
      },
      createdAt: '2026-06-27T10:30:00',
      updatedAt: '2026-06-27T10:30:00',
    },
  ],
};
